Aplicaciones/informativa/urls.py
from django.urls import path
from .views import landing_page

urlpatterns = [
    path('', landing_page, name='landing_page'),  # Esta será la vista principal
]

Aplicaciones/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('welcome/', views.welcome_view, name='welcome'),  # Nueva URL para la vista de bienvenida
    path('logout/', views.logout_view, name='logout'),  # Asegúrate de tener esta línea
]

historial_clinico/urls.py
# from django.contrib import admin
# from django.urls import include, path

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', include('Aplicaciones.informativa.urls')),
#     path('usuarios/', include('Aplicaciones.usuarios.urls')),  # URLs de usuarios}
#     # Agrega las rutas para las otras aplicaciones
#     path('admisionistas/', include('Aplicaciones.admisionistas.urls')),  # Rutas para el proyecto de admisionistas
#     path('gestion_pacientes/', include('Aplicaciones.gestion_pacientes.urls')),  # Rutas para el proyecto de doctores
#     path('accounts/', include('django.contrib.auth.urls'))
# ]

from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from historial_clinico import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Aplicaciones.informativa.urls')),
    path('usuarios/', include('Aplicaciones.usuarios.urls')),  # URLs de usuarios
    path('admisionistas/', include('Aplicaciones.admisionistas.urls')),
    path('gestion_pacientes/', include('Aplicaciones.gestion_pacientes.urls')),
    path('administradores/', include('Aplicaciones.administradores.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Aplicaciones/informativa/views.py
from django.shortcuts import render

def landing_page(request):
    return render(request, 'informativa/landing_page.html')

Aplicaciones/informativa/templates/informativa/plantillainformativa.html
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Centro Médico Renacer</title>
  <meta name="description" content="">
  <meta name="keywords" content="">

  <!-- Favicons -->
  <link href="{% static 'plantilla/medilab/assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'plantilla/medilab/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'plantilla/medilab/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'plantilla/medilab/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'plantilla/medilab/assets/vendor/aos/aos.css'%}" rel="stylesheet">
  <link href="{% static 'plantilla/medilab/assets/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="{% static 'plantilla/medilab/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'plantilla/medilab/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{% static 'plantilla/medilab/assets/css/main.css' %}" rel="stylesheet">
  
</head>

<body class="index-page">

  <header id="header" class="header sticky-top">

    <div class="topbar d-flex align-items-center">
      <div class="container d-flex justify-content-center justify-content-md-between">
        <div class="contact-info d-flex align-items-center">
          <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:contact@example.com">centromedicorenacer@gmail.com</a></i>
          <i class="bi bi-phone d-flex align-items-center ms-4"><span>+593 098 492 4236</span></i>
        </div>
        <div class="social-links d-none d-md-flex align-items-center">          
          <a href="https://www.facebook.com/CMRENACER/?locale=es_LA" class="facebook"><i class="bi bi-facebook"></i></a>
          <a href="https://www.instagram.com/centromedicorenacerr/" class="instagram"><i class="bi bi-instagram"></i></a>          
          <a href="{% url 'usuarios:login' %}" class="linkedin"><i class="bi bi-person-circle"></i> INICIAR SESIÓN</a>
        </div>
      </div>
    </div><!-- End Top Bar -->

    <div class="branding d-flex align-items-center">

      <div class="container position-relative d-flex align-items-center justify-content-between">
        <a href="{% url 'landing_page' %}" class="logo d-flex align-items-center me-auto">
          <!-- Uncomment the line below if you also wish to use an image logo -->
          <!-- <img src="assets/img/logo.png" alt=""> -->
          <h1 class="sitename">Renacer</h1>
        </a>

        <nav id="navmenu" class="navmenu">
          <ul>
            <li><a href="#hero" class="active">Inicio<br></a></li>
            <li><a href="#about">Sobre Nosotros</a></li>
            <li><a href="#services">Servicios</a></li>
            <li><a href="#departments">Especialidades</a></li>
            <li><a href="#doctors">Doctores</a></li>            
            <li><a href="#contact">Contactos</a></li>
          </ul>
          <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
        </nav>

        

      </div>

    </div>

  </header>
  {% block body %}

  {% endblock %}
  <footer id="footer" class="footer light-background">

    <div class="container footer-top">
      <div class="row gy-4">
        <div class="col-lg-4 col-md-6 footer-about">
          <a href="{% url 'landing_page' %}" class="logo d-flex align-items-center">
            <span class="sitename">Centro Médico Renacer</span>
          </a>
          <div class="footer-contact pt-3">          
            <p>Av. Maldonado S52-325, entre Reinaldo Santacruz y Nicolás Zingles, Guamaní.</p>
            <p>Quito, Ecuador</p>
            <p class="mt-3"><strong>Teléfono:</strong> <span>+593 098 492 4236</span></p>
            <p><strong>Email:</strong> <span>info@example.com</span></p>
          </div>
          <div class="social-links d-flex mt-4">                          
            <a href="https://www.facebook.com/CMRENACER/?locale=es_LA"><i class="bi bi-facebook"></i></a>
            <a href="https://www.instagram.com/centromedicorenacerr/"><i class="bi bi-instagram"></i></a>            
          </div>
        </div>

        <div class="col-lg-6 col-md-12 footer-links">
          <h4>Links Útiles</h4>
          <ul>
            <li><a href="#">Inicio</a></li>
            <li><a href="#">Sobre Nosotros</a></li>
            <li><a href="#">Especialidades</a></li>
            <li><a href="#">Servicios</a></li>            
          </ul>
        </div>                    
      </div>
    </div>

    <div class="container copyright text-center mt-4">
      <p>© <span>Copyright</span> <strong class="px-1 sitename">Centro Médico Renacer</strong> <span>Todos los derechos reservados.</span></p>
      <div class="credits">        
        <b>Desarrollado por:</b> Michael Llumiugsi & Lenin Flores
      </div>
    </div>

  </footer>

  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'plantilla/medilab/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'plantilla/medilab/assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'plantilla/medilab/assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'plantilla/medilab/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'plantilla/medilab/assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'plantilla/medilab/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>

  <!-- Main JS File -->
  <script src="{% static 'plantilla/medilab/assets/js/main.js' %}"></script>

</body>
</html>