Aplicaciones/administradores/urls.py
from django.urls import include, path
from . import views

app_name = 'administradores'

urlpatterns = [    
    path('inicio_administrador/', views.inicio_administrador, name='inicio_administrador'),
    path('gestion_usuarios/', views.gestion_usuarios, name='gestion_usuarios'),
    path('obtener_usuarios/', views.obtener_usuarios, name='obtener_usuarios'),
    path('agregar_usuario/', views.agregar_usuario, name='agregar_usuario'),
    path('eliminar_usuario/<int:usuario_id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('obtener_usuario/<int:usuario_id>/', views.obtener_usuario, name='obtener_usuario'),
    path('admisionistas/', include('Aplicaciones.admisionistas.urls')),
    path('validar_username/', views.validar_username, name='validar_username'),
    path('validar_username_actualizar/', views.validar_username_actualizar, name='validar_username_actualizar'),
    path('obtener_usuario_edit/<int:usuario_id>/', views.obtener_usuario_edit, name='obtener_usuario_edit'),
    path('actualizar_usuario/', views.actualizar_usuario, name='actualizar_usuario'),
]

Aplicaciones/admisionistas/urls.py
from django.urls import path
from django.views.generic import TemplateView

from Aplicaciones.admisionistas import views

app_name = 'admisionistas'

urlpatterns = [
    #INGRESO PACIENTES
    path('ingreso_pacientes/', views.ingreso_pacientes, name='ingreso_pacientes'),
    path('agregar_paciente/', views.agregar_paciente, name='agregar_paciente'),
    path('obtener_paciente/<int:paciente_id>/', views.obtener_paciente, name='obtener_paciente'),
    path('actualizar_paciente/', views.actualizar_paciente, name='actualizar_paciente'),  # Nueva ruta para actualizar
    path('eliminar_paciente/<int:paciente_id>/', views.eliminar_paciente, name='eliminar_paciente'),
    path('verificar_cedula/', views.verificar_cedula, name='verificar_cedula'),
    path('verificar_cedula_actualizar/', views.verificar_cedula_actualizar, name='verificar_cedula_actualizar'),
    path('buscar_pacientes/', views.buscar_pacientes, name='buscar_pacientes'),
    # ASIGAR CITAS
    path('registro_citas/', views.registro_citas, name='registro_citas'),
    path('registrar_cita/', views.registrar_cita, name='registrar_cita'),
    path('cargar_citas/', views.cargar_citas, name='cargar_citas'),
    path('eliminar_cita/<int:id_cita>/', views.eliminar_cita, name='eliminar_cita'),
    #HISTORIAL CITAS
    path('historial_citas/', views.historial_citas, name='historial_citas'),
    path('cargar_historial_citas/', views.cargar_historial_citas, name='cargar_historial_citas'),
    #VERIFICAR ESTADO DE LAS CITAS
    path('verificar_estado_cita/<int:id_cita>/', views.verificar_estado_cita, name='verificar_estado_cita'),
    #CANCELAR CITA
    path('cancelar_cita/<int:id_cita>/', views.cancelar_cita, name='cancelar_cita'),
    #DASHBOARD    
    path('dashboard_citas/', views.dashboard_citas, name='dashboard_citas'),



]

Aplicaciones/gestion_pacientes/urls.py
from django.urls import path
from . import views
app_name = 'gestion_pacientes'

urlpatterns = [
    path('manejo_pacientes/', views.manejo_pacientes, name='manejo_pacientes'),
    path('inicio_doctor/', views.inicio_doctor, name='inicio_doctor'),
    path('citas/', views.citas, name='citas'),
    path('cargar_citas/', views.cargar_citas, name='cargar_citas'),
    path('registro_cita/<int:id_cita>/', views.registro_cita, name='registro_cita'),
    path('cancelar_cita/<int:id_cita>/', views.cancelar_cita, name='cancelar_cita'),
    path('historias_clinicas/', views.historias_clinicas, name='historias_clinicas'),
    path('ver-historial-clinico/<int:id_paciente>/', views.ver_historial_clinico, name='ver_historial_clinico'),
]

Aplicaciones/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('welcome/', views.welcome_view, name='welcome'),  # Nueva URL para la vista de bienvenida
    path('logout/', views.logout_view, name='logout'),  # Asegúrate de tener esta línea
]

historial_clinico/urls.py
# from django.contrib import admin
# from django.urls import include, path

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', include('Aplicaciones.informativa.urls')),
#     path('usuarios/', include('Aplicaciones.usuarios.urls')),  # URLs de usuarios}
#     # Agrega las rutas para las otras aplicaciones
#     path('admisionistas/', include('Aplicaciones.admisionistas.urls')),  # Rutas para el proyecto de admisionistas
#     path('gestion_pacientes/', include('Aplicaciones.gestion_pacientes.urls')),  # Rutas para el proyecto de doctores
#     path('accounts/', include('django.contrib.auth.urls'))
# ]

from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from historial_clinico import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Aplicaciones.informativa.urls')),
    path('usuarios/', include('Aplicaciones.usuarios.urls')),  # URLs de usuarios
    path('admisionistas/', include('Aplicaciones.admisionistas.urls')),
    path('gestion_pacientes/', include('Aplicaciones.gestion_pacientes.urls')),
    path('administradores/', include('Aplicaciones.administradores.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

historial_clinico/templates/plantilla.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Centro Médico Renacer</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'plantilla/mazer/dist/assets/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'plantilla/mazer/dist/assets/vendors/perfect-scrollbar/perfect-scrollbar.css'%}">
    <link rel="stylesheet" href="{% static 'plantilla/mazer/dist/assets/vendors/bootstrap-icons/bootstrap-icons.css'%}">
    <link rel="stylesheet" href="{% static 'plantilla/mazer/dist/assets/css/app.css'%}">
    <link rel="shortcut icon" href="{% static 'plantilla/mazer/dist/assets/images/favicon.svg'%}" type="image/x-icon">
    
    <!-- Cargar Sweet Alert -->
    <link rel="stylesheet" href="{% static 'plantilla/mazer/dist/assets/vendors/sweetalert2/sweetalert2.min.css' %}">
    <!-- Cargar Toastify -->
    <link rel="stylesheet" href="{% static 'plantilla/mazer/dist/assets/vendors/toastify/toastify.css' %}">
    
    <!-- Cargar Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">
    <!--Cargar CSS propio-->
    <link rel="stylesheet" href="{% static 'css/ingreso_pacientes.css' %}">
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    
</head>

<body>
    <div id="app">
        <div id="sidebar" class="active">
            <div class="sidebar-wrapper active">
                <div class="sidebar-header">
                    <div class="d-flex justify-content-between">
                        <div class="logo">
                            <a href="{% if request.user.tipo_usuario == 'administrador' %}
                                         {% url 'administradores:inicio_administrador' %}
                                      {% elif request.user.tipo_usuario == 'admisionista' %}
                                         {% url 'admisionistas:ingreso_pacientes' %}
                                      {% else %}
                                         #{% endif %}">
                                <img src="{% static 'plantilla/mazer/dist/assets/images/logo/logo.png' %}" alt="Logo" srcset="">
                            </a>
                        </div>
                        <div class="toggler">
                            <a style="color: white; !important" href="#" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
                        </div>
                    </div>
                </div>
                <div class="sidebar-menu">
                    <ul class="menu">
                        <li class="sidebar-title">Menú Principal</li>
                        <li class="sidebar-item">
                            <a href="{% url 'admisionistas:ingreso_pacientes' %}" class='sidebar-link'>
                                <i class="bi bi-person-circle"></i>
                                <span>Gestión de Pacientes</span>
                            </a>
                        </li>  
                        <li class="sidebar-item">
                            <a href="{% url 'admisionistas:registro_citas' %}" class='sidebar-link'>
                                <i class="bi bi-person-circle"></i>
                                <span>Asignaciones de hoy</span>
                            </a>
                        </li>   
                        <li class="sidebar-item">
                            <a href="{% url 'admisionistas:historial_citas' %}" class='sidebar-link'>
                                <i class="bi bi-person-circle"></i>
                                <span>Historial de Asignaciones</span>
                            </a>
                        </li>    
                        <li class="sidebar-item  ">
                            <a href="{% url 'admisionistas:dashboard_citas' %}" class='sidebar-link'>
                                <i class="bi bi-grid-fill"></i>
                                <span>Dashboard</span>
                            </a>
                        </li>   
                    </ul>
                </div>
                <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
            </div>
        </div>
        <div id="main" class='layout-navbar'>
            <header class='mb-3'>
                <nav class="navbar navbar-expand navbar-light ">
                    <div class="container-fluid">
                        <a href="#" class="burger-btn d-block">
                            <i class="bi bi-justify fs-3"></i>
                        </a>

                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                                <li class="nav-item dropdown me-1">
                                    <a class="nav-link active dropdown-toggle" href="#" data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                        <i class='bi bi-envelope bi-sub fs-4 text-gray-600'></i>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                                        <li>
                                            <h6 class="dropdown-header">Mail</h6>
                                        </li>
                                        <li><a class="dropdown-item" href="#">No new mail</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown me-3">
                                    <a class="nav-link active dropdown-toggle" href="#" data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                        <i class='bi bi-bell bi-sub fs-4 text-gray-600'></i>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                                        <li>
                                            <h6 class="dropdown-header">Notifications</h6>
                                        </li>
                                        <li><a class="dropdown-item">No notification available</a></li>
                                    </ul>
                                </li>
                            </ul>
                            <div class="dropdown">
                                <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                    <div class="user-menu d-flex">
                                        <div class="user-name text-end me-3">
                                            <h6 class="mb-0 text-gray-600">{{ user.first_name }} {{ user.last_name }}</h6>
                                            <p class="mb-0 text-sm text-gray-600">{{ user.tipo_usuario }}</p>
                                        </div>
                                        <div class="user-img d-flex align-items-center">
                                            <div class="avatar avatar-md">
                                                <img src="{{ user.image.url }}" alt="Imagen de perfil" style="width: 40px; height: 40px; border-radius: 40%;">
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                                    <li>
                                        <h6 class="dropdown-header">Hola! {{ user.username }}</h6>                                        
                                    </li>
                                    <li><a class="dropdown-item" href="#"><i class="icon-mid bi bi-person me-2"></i> Mi
                                            Perfil</a></li>
                                    <li><a class="dropdown-item" href="#"><i class="icon-mid bi bi-gear me-2"></i>
                                            Configuraciones</a></li>                                    
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'usuarios:logout' %}"><i class="icon-mid bi bi-box-arrow-left me-2"></i> Cerrar Sesión </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </nav>
            </header>
            <div id="main-content">

                <div class="page-heading">
                    
                    <section class="section">
                        <!-- Contenido principal -->
                    <div class="container mt-4">
                        {% block content %}
                        <!-- Aquí irá el contenido específico de cada página -->
                        {% endblock %}
                    </div>
                    <!--
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Example Content</h4>
                            </div>
                            
                            <div class="card-body">
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur quas omnis
                                laudantium tempore
                                exercitationem, expedita aspernatur sed officia asperiores unde tempora maxime odio
                                reprehenderit
                                distinctio incidunt! Vel aspernatur dicta consequatur!
                            </div>
                            <i class="bi-arrow-up-short">asdas</i>
                        </div>
                        -->
                        <br><br>
                        <br><br>

                    </section>
                </div>

            
            </div>
        </div>
    </div>
    <script src="{% static 'plantilla/mazer/dist/assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'plantilla/mazer/dist/assets/js/bootstrap.bundle.min.js'%} "></script>
    <script src="{% static 'plantilla/mazer/dist/assets/js/main.js' %}"></script>
    <!--SCRIP SWEET ALERT-->
    <script src="{% static 'plantilla/mazer/dist/assets/vendors/sweetalert2/sweetalert2.all.min.js' %}"></script>
    
    <!--SCRIPT TOASTIFY-->
    <script src="{% static 'plantilla/mazer/dist/assets/vendors/toastify/toastify.js' %}"></script>
    <!-- Scripts -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/datatables.min.js' %}"></script>
    <script src="{% static 'js/ingreso_pacientes.js' %}"></script>
    <script src="{% static 'js/registro_citas.js' %}"></script>
    <script src="{% static 'js/historial_citas.js' %}"></script>
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/es.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/messages_es.js' %}"></script>
    <script src="{% static 'js/chart.js.js' %}"></script>



    <!--<script src="{% static 'js/app.js' %}"></script>  Script personalizado -->

    

</body>

</html>

historial_clinico/templates/plantilla2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}CENTRO MEDICO RENACER{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <!-- Cargar Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!--<link rel="stylesheet" href="{% static 'css/style.css' %}">  Estilo personalizado -->
</head>
<!-- Contenido principal -->
<div class="container mt-4">
    {% block content %}
    <!-- Aquí irá el contenido específico de cada página -->
    {% endblock %}
</div>

    <!-- Scripts -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/no_ir_atras.js' %}"></script>    
    <!--<script src="{% static 'js/app.js' %}"></script>  Script personalizado -->
</body>
</html>

historial_clinico/templates/plantillaadministradores.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Centro Médico Renacer</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'plantilla/mazer/dist/assets/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'plantilla/mazer/dist/assets/vendors/perfect-scrollbar/perfect-scrollbar.css'%}">
    <!--Cargar Font Awesome-->
    <link rel="stylesheet" href="{% static 'plantilla/mazer/dist/assets/vendors/fontawesome/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'plantilla/mazer/dist/assets/vendors/bootstrap-icons/bootstrap-icons.css'%}">
    
    <link rel="stylesheet" href="{% static 'plantilla/mazer/dist/assets/css/app.css'%}">
    <link rel="shortcut icon" href="{% static 'plantilla/mazer/dist/assets/images/favicon.svg'%}" type="image/x-icon">
        
    <!-- Cargar Sweet Alert -->
    <link rel="stylesheet" href="{% static 'plantilla/mazer/dist/assets/vendors/sweetalert2/sweetalert2.min.css' %}">
    <!-- Cargar Toastify -->
    <link rel="stylesheet" href="{% static 'plantilla/mazer/dist/assets/vendors/toastify/toastify.css' %}">
    
    <!-- Cargar Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">
    
    
</head>

<body>
    <div id="app">
        <div id="sidebar" class="active">
            <div class="sidebar-wrapper active">
                <div class="sidebar-header">
                    <div class="d-flex justify-content-between">
                        <div class="logo">
                            <a href="{% if request.user.tipo_usuario == 'administrador' %}
                                         {% url 'administradores:inicio_administrador' %}
                                      {% elif request.user.tipo_usuario == 'admisionista' %}
                                         {% url 'admisionistas:inicio_admisionista' %}
                                      {% else %}
                                         #{% endif %}">
                                <img src="{% static 'plantilla/mazer/dist/assets/images/logo/logo.png' %}" alt="Logo" srcset="">
                            </a>
                        </div>
                        <div class="toggler">
                            <a style="color: white; !important" href="#" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
                        </div>
                    </div>
                </div>
                <div class="sidebar-menu">
                    <ul class="menu">
                        <li class="sidebar-title">Menú Principal</li>
                                    
                        <li class="sidebar-item  ">
                            <a href="{% url 'administradores:inicio_administrador' %}" class='sidebar-link'>
                                <i class="bi bi-house-fill" style="font-size: 20px;"></i>
                                <span>Inicio</span>
                            </a>
                        </li>                                      
                        <li class="sidebar-item ">                            
                            <a href="{% url 'admisionistas:buscar_pacientes' %}" class='sidebar-link'>                                
                                <i class="bi bi-person" style="font-size: 20px;"></i>
                                <span>Pacientes</span>
                            </a>
                            <a href="#" class='sidebar-link'>                                
                                <i class="bi bi-journal-medical" style="font-size: 20px;"></i>
                                <span>Historias Clínicas</span>
                            </a>
                            <a href="{% url 'administradores:gestion_usuarios' %}" class='sidebar-link'>                                
                                <i class="bi bi-person-badge-fill" style="font-size: 20px;"></i>
                                <span>Usuarios</span>
                            </a>                            
                        </li>                                                             
                    </ul>
                </div>
                <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
            </div>
        </div>
        <div id="main" class='layout-navbar'>
            <header class='mb-3'>
                <nav class="navbar navbar-expand navbar-light ">
                    <div class="container-fluid">
                        <a href="#" class="burger-btn d-block">
                            <i class="bi bi-justify fs-3"></i>
                        </a>

                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">                                
                                <li class="nav-item dropdown me-3">
                                    <a class="nav-link active dropdown-toggle" href="{% url 'administradores:inicio_administrador' %}"
                                        aria-expanded="false">
                                        <i class='bi bi-house-door bi-sub fs-4 text-gray-600'></i>
                                    </a>                                    
                                </li>
                            </ul>
                            <div class="dropdown">
                                <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                    <div class="user-menu d-flex">
                                        <div class="user-name text-end me-3">
                                            <h6 class="mb-0 text-gray-600">{{ user.first_name }} {{ user.last_name }}</h6>
                                            <p class="mb-0 text-sm text-gray-600">{{ user.tipo_usuario }}</p>
                                        </div>
                                        <div class="user-img d-flex align-items-center">
                                            <div class="avatar avatar-md">
                                                {% if user.image %}
                                                    <img src="{{ user.image.url }}" alt="Imagen de perfil" style="width: 40px; height: 40px; border-radius: 40%;">
                                                {% else %}
                                                    <img src="{% static 'plantilla/mazer/dist/assets/images/logo/logo.png' %}" alt="Imagen predeterminada" style="width: 40px; height: 40px; border-radius: 40%;">
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                                    <li>
                                        <h6 class="dropdown-header">Hola! {{ user.username }}</h6>                                        
                                    </li>
                                    <li><a class="dropdown-item" href="#"><i class="icon-mid bi bi-person me-2"></i> Mi
                                            Perfil</a></li>
                                    <li><a class="dropdown-item" href="#"><i class="icon-mid bi bi-gear me-2"></i>
                                            Configuraciones</a></li>                                    
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'usuarios:logout' %}"><i class="icon-mid bi bi-box-arrow-left me-2"></i> Cerrar Sesión </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </nav>
            </header>
            <div id="main-content">

                <div class="page-heading">
                    
                    <section class="section">
                        <!-- Contenido principal -->
                    <div class="container mt-4">
                        {% block content %}
                        <!-- Aquí irá el contenido específico de cada página -->
                        {% endblock %}
                    </div>
                    <!--
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Example Content</h4>
                            </div>
                            <div class="card-body">
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur quas omnis
                                laudantium tempore
                                exercitationem, expedita aspernatur sed officia asperiores unde tempora maxime odio
                                reprehenderit
                                distinctio incidunt! Vel aspernatur dicta consequatur!
                            </div>
                            <i class="bi-arrow-up-short">asdas</i>
                        </div>
                        -->
                    </section>
                </div>

                
            </div>
        </div>
    </div>
    <!--SCRIPT FONT AWESOME-->
    <script src="{% static 'plantilla/mazer/dist/assets/vendors/fontawesome/all.min.js' %}"></script>
    <script src="{% static 'plantilla/mazer/dist/assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'plantilla/mazer/dist/assets/js/bootstrap.bundle.min.js'%} "></script>
    <script src="{% static 'plantilla/mazer/dist/assets/js/main.js' %}"></script>
    
    <!--SCRIP SWEET ALERT-->
    <script src="{% static 'plantilla/mazer/dist/assets/vendors/sweetalert2/sweetalert2.all.min.js' %}"></script>
    
    <!--SCRIPT TOASTIFY-->
    <script src="{% static 'plantilla/mazer/dist/assets/vendors/toastify/toastify.js' %}"></script>
    <!-- Scripts -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/datatables.min.js' %}"></script>
    <!-- <script src="{% static 'js/ingreso_pacientes.js' %}"></script> -->
    <script src="{% static 'js/ingreso_usuarios.js' %}"></script>
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/es.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/contrasenia.js' %}"></script>

    <!-- Scripts -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/no_ir_atras.js' %}"></script>

</body>

</html>